name: Build and Deploy

on:
    workflow_dispatch: {}

permissions:
    id-token: write
    contents: read

env: # need pass in .env variables to make available for workflow during build
    AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    AWS_IAMROLE_GITHUB: ${{ vars.AWS_IAMROLE_GITHUB }}
    AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4 # need setup github role for repo

            - name: Setup pnpm and Node
              uses: pnpm/setup@v2.1.0
              with:
                  version: ^11.0.9
                  node-version: 'node@20'
                  cache: true

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_IAMROLE_GITHUB }}
                  role-session-name: GitHub-Action-Role
                  aws-region: ${{ env.AWS_REGION }}

            - name: Deploy CDK Stack
              run: pnpm cdk deploy AwsCdkAppStack --require-approval never
